#!/usr/bin/env bash
# description: Verify canonical Markdown output routes generated by Hugo.
set -eufo pipefail

TOPDIR=$(git rev-parse --show-toplevel)
BUILD_DIR=${1:-${TOPDIR}/tmp/docs-build-test}
CONTENT_DIR=${TOPDIR}/docs/content

fail() {
  echo "Markdown output check failed: $*" >&2
  exit 1
}

[[ -d ${BUILD_DIR} ]] || fail "build directory does not exist: ${BUILD_DIR}"

while IFS= read -r source; do
  relative=${source#"${CONTENT_DIR}/"}
  [[ ${relative} == "_index.md" ]] && continue

  section=${relative%/_index.md}
  native=${BUILD_DIR}/${section}/index.md
  canonical=${BUILD_DIR}/${section}.md
  html=${BUILD_DIR}/${section}/index.html

  [[ -f ${native} ]] || fail "missing native section output: ${native}"
  [[ -f ${canonical} ]] || fail "missing canonical section output: ${canonical}"
  cmp -s "${native}" "${canonical}" ||
    fail "section outputs differ: ${native} and ${canonical}"
  [[ -f ${html} ]] || fail "missing section HTML output: ${html}"
  grep -Fq "type=text/markdown href=/${section}.md" "${html}" ||
    grep -Fq "type=\"text/markdown\" href=\"/${section}.md\"" "${html}" ||
    fail "section alternate link is not canonical: ${html}"
done < <(find "${CONTENT_DIR}" -name _index.md -type f | sort)

[[ -f ${BUILD_DIR}/docs/getting-started.md ]] ||
  fail "missing regular page Markdown output"
grep -Fq "](/docs/cli.md)" "${BUILD_DIR}/docs/installation/kubernetes.md" ||
  fail "generated Markdown link to a section is not canonical"

echo "Markdown output routes are valid."
